FROM calaos-os:latest

RUN curl -sS https://archive.raspberrypi.org/debian/raspberrypi.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/spotify.gpg
RUN echo 'deb https://archive.raspberrypi.org/debian bullseye main contrib non-free' >> /etc/apt/sources.list

RUN apt -y update && \
    apt -y upgrade && \
    apt-get install -yq --no-install-recommends \
        raspi-config raspi-utils raspberrypi-bootloader  \
        raspberrypi-kernel raspberrypi-net-mods raspberrypi-sys-mods
