#!/usr/bin/ash

# args: partition device (/dev/sda1)
get_device_from_part() {
    local part="${1}"
    part=${part#/dev/}
    local disk=$(readlink /sys/class/block/$part)
    disk=${disk%/*}
    disk=/dev/${disk##*/}
    echo $disk
}

run_latehook() {
    local rootfs_dev=$(resolve_device "$root"); # resolve devices for blkid

    if [ "$LABEL" = "live" ] || [ "$LABEL" = "live-efi" ]
    then
        msg ":: Entering Calaos OS Hook"

        if [[ "$rootfs_dev" ]]
        then
            msg ":: Found rootfs on device: $rootfs_dev"

            local uuid=$(echo $rootfs_dev | cut -d/ -f5)
            msg ":: Found UUID: $uuid"

            local dev=$(blkid --uuid $uuid)
            msg ":: Found rootfs dev: $dev"

            #rootfs is partition 2
            local partnum=2
            local rootdisk=$(get_device_from_part ${dev})

            msg ":: Found rootfs disk: $rootdisk"

            #check if we need to resize rootfs partition to USB drive
            if out=$(growpart --dry-run "${rootdisk}" "${partnum}") ; then
                msg ":: Resizing rootfs to fill disk"
                growpart --update auto "${rootdisk}" "${partnum}"
                sleep 1
                e2fsck -pf "${dev}"
                sleep 1
                resize2fs "${dev}"
	        fi
        fi
    fi
}
