name: Build Calaos-OS
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: calaos-os
        tags: v1 ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
