name: Repository Dispatch

on:
  repository_dispatch:
    types: [build_pkg]

jobs:
  buildEvent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Import secrets
        run: |
          cat > gpg-key.asc <<- 'EOF'
          ${{ secrets.GPG_PRIVATE_KEY }}
          EOF
          cat > passphrase.txt <<- 'EOF'
          ${{ secrets.GPG_PASSPHRASE }}
          EOF
          cat > upload_token <<- 'EOF'
          ${{ secrets.UPLOAD_TOKEN }}
          EOF
        shell: bash

      - name: make-pkgs-${{ github.event.client_payload.pkgname }}
        run: make build-${{ github.event.client_payload.pkgname }} REPO=${{ github.event.client_payload.repo }} ARCH=${{ github.event.client_payload.arch }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: out/pkg/*/*
