name: Build zigbee2mqtt

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo (calaos, calaos-dev)'
        required: true
        default: 'calaos-dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/calaos-build
          event-type: build_pkg
          client-payload: '{"pkgname": "zigbee2mqtt", "repo": "${{ github.event.inputs.repo }}" }'
