name: Build Calaos-OS
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      vincrement:
        description: 'Package version increment (major.minor.xxx)'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          # - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calaos Action Bump Version
        id: calaos_version
        uses: calaos/action-bump-version@1.2.2
        with:
          version_fragment: ${{ github.event.inputs.vincrement || 'prerelease' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build calaos-os
        run: |
          make calaos-os TARGET_ARCH=${{ matrix.platform }} VERSION=${{ steps.calaos_version.outputs.version_bumped }}

      - name: Create a Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.calaos_version.outputs.version_bumped }}
          name: ${{ steps.calaos_version.outputs.version_bumped }}
          prerelease: ${{ github.event.inputs.vincrement == '' || github.event.inputs.vincrement == 'prerelease' }}
          files: out/*.zst
          gzip: false
