name: Build Calaos-OS
on:
  push:
    branches:
      - "main"


jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: calaos-os-builder:latest
          outputs: type=docker,dest=/tmp/calaos-os-builder.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: calaos-os-builder
          path: /tmp/calaos-os-builder.tar

  build:
    runs-on: ubuntu-latest
    needs: image
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: calaos-os-builder
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/calaos-os-builder.tar
          docker image ls -a