name: Repository Dispatch
on:
  repository_dispatch:
    types: [build_pkg]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: echo ${{ github.event.client_payload }}
      - name: make-pkgs-${{ github.event.client_payload.pkgname }}
        run: make build-${{ github.event.client_payload.pkgname }}
