name: Build zigbee2mqtt

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo (calaos, calaos-dev)'
        required: true
        default: 'calaos-dev'
      arch:
        description: 'Arch'
        required: true
        default: 'x86_64'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/calaos-build
          event-type: build_pkg
          client-payload: '{"pkgname": "zigbee2mqtt", "repo": "${{ github.event.inputs.repo }}", "arch": "${{ github.event.inputs.arch }}" }'