name: Repository Dispatch

on:
  repository_dispatch:
    types: [build_pkg]

jobs:
  buildEvent:
    runs-on: ubuntu-latest

    steps:
      - name: Import secrets
        run: |
          echo -e ${{ secrets.GPG_PRIVATE_KEY }} > gpg-key.asc
          echo -e ${{ secrets.GPG_PASSPHRASE }} > passphrase.txt
          echo -e ${{ secrets.UPLOAD_TOKEN }} > upload_token
        shell: bash
      - uses: actions/checkout@v2
      - name: debug
        run: echo ${{ github.event.client_payload }}
      - name: make-pkgs-${{ github.event.client_payload.pkgname }}
        run: make build-${{ github.event.client_payload.pkgname }}
