name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      
    - name: make-pkgs-zigbee2mqtt
      run: make build-zigbee2mqtt
    - name: make-pkgs-owfs
      run: make build-owfs
    - name: make-pkgs-ola
      run: make build-ola
    - name: make-pkgs-linuxconsoletols
      run: make build-linuxconsoletools
    - name: make-pkgs-knxd
      run: make build-knxd
    - name: make-pkgs-calaos-ddns
      run: make build-calaos-ddns
    - name: make-pkgs-calaos-web-app
      run: make calaos-web-app
    - name: make-pkgs-calaos-server
      run: make calaos-server
    - name: make-pkgs-calaos-home
      run: make calaos-home
    - name: make-iso
      run: make build-iso
      
